name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm i

    - name: Run TypeScript compilation
      run: npx tsc

    - name: Run tests
      run: npx vitest run
